runtime: python311

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
  
env_variables:
  REDISHOST: '10.236.247.51'
  REDISPORT: '6379'

vpc_access_connector:
  name: projects/letter-boxed-solver/locations/us-east1/connectors/cache-connector

automatic_scaling:
  max_instances: 4
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  min_pending_latency: 250ms